# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: true
        tags:
          - { name: twig.extension }