/**
 * InPlace-Editor classes defined here.
 */
export declare const ROOT: string;
export declare const ROOT_TIP: string;
export declare const VALUE_WRAPPER: string;
export declare const VALUE: string;
export declare const OVERLAY_ICON: string;
export declare const TIP_TITLE: string;
export declare const TITLE: string;
export declare const INLINE: string;
export declare const POPUP: string;
export declare const WRAPPER: string;
export declare const LOADING: string;
export declare const FORM: string;
export declare const CTRL_GROUP: string;
export declare const INPUT: string;
export declare const BUTTONS: string;
export declare const EDITABLE_ERROR: string;
export declare const ELEMENTS: string;
export declare const OPEN: string;
export declare const BTN_SAVE: string;
export declare const BTN_CANCEL: string;
export declare const RTE_SPIN_WRAP: string;
export declare const CTRL_OVERLAY: string;
export declare const DISABLE: string;
export declare const ICONS: string;
export declare const PRIMARY: string;
export declare const SHOW: string;
export declare const HIDE: string;
export declare const RTL: string;
export declare const ERROR: string;
export declare const LOAD: string;
