/**
 * Specifies pivot external events

 */
export declare const load: string;
export declare const enginePopulating: string;
export declare const enginePopulated: string;
export declare const onFieldDropped: string;
export declare const beforePivotTableRender: string;
export declare const afterPivotTableRender: string;
export declare const beforeExport: string;
export declare const excelHeaderQueryCellInfo: string;
export declare const pdfHeaderQueryCellInfo: string;
export declare const excelQueryCellInfo: string;
export declare const pdfQueryCellInfo: string;
export declare const onPdfCellRender: string;
export declare const dataBound: string;
export declare const queryCellInfo: string;
export declare const headerCellInfo: string;
export declare const hyperlinkCellClick: string;
export declare const resizing: string;
export declare const resizeStop: string;
export declare const cellClick: string;
export declare const drillThrough: string;
export declare const beforeColumnsRender: string;
export declare const selected: string;
export declare const cellSelecting: string;
export declare const drill: string;
export declare const cellSelected: string;
export declare const cellDeselected: string;
export declare const rowSelected: string;
export declare const rowDeselected: string;
export declare const beginDrillThrough: string;
export declare const saveReport: string;
export declare const fetchReport: string;
export declare const loadReport: string;
export declare const renameReport: string;
export declare const removeReport: string;
export declare const newReport: string;
export declare const toolbarRender: string;
export declare const toolbarClick: string;
export declare const chartTooltipRender: string;
export declare const chartLoaded: string;
export declare const chartLoad: string;
export declare const chartResized: string;
export declare const chartAxisLabelRender: string;
export declare const chartSeriesCreated: string;
export declare const aggregateCellInfo: string;
export declare const contextMenuClick: string;
export declare const contextMenuOpen: string;
export declare const fieldListRefreshed: string;
export declare const conditionalFormatting: string;
export declare const beforePdfExport: string;
export declare const beforeExcelExport: string;
/**
 * Specifies pivot internal events
 */
export declare const initialLoad: string;
export declare const uiUpdate: string;
export declare const scroll: string;
export declare const contentReady: string;
export declare const dataReady: string;
export declare const initSubComponent: string;
export declare const treeViewUpdate: string;
export declare const pivotButtonUpdate: string;
export declare const initCalculatedField: string;
export declare const click: string;
export declare const initToolbar: string;
export declare const initFormatting: string;
