/**
 * Specifies pivot external events

 */
export var load = 'load';
export var enginePopulating = 'enginePopulating';
export var enginePopulated = 'enginePopulated';
export var onFieldDropped = 'onFieldDropped';
export var beforePivotTableRender = 'beforePivotTableRender';
export var afterPivotTableRender = 'afterPivotTableRender';
export var beforeExport = 'beforeExport';
export var excelHeaderQueryCellInfo = 'excelHeaderQueryCellInfo';
export var pdfHeaderQueryCellInfo = 'pdfHeaderQueryCellInfo';
export var excelQueryCellInfo = 'excelQueryCellInfo';
export var pdfQueryCellInfo = 'pdfQueryCellInfo';
export var onPdfCellRender = 'onPdfCellRender';
export var dataBound = 'dataBound';
export var queryCellInfo = 'queryCellInfo';
export var headerCellInfo = 'headerCellInfo';
export var hyperlinkCellClick = 'hyperlinkCellClick';
export var resizing = 'resizing';
export var resizeStop = 'resizeStop';
export var cellClick = 'cellClick';
export var drillThrough = 'drillThrough';
export var beforeColumnsRender = 'beforeColumnsRender';
export var selected = 'selected';
export var cellSelecting = 'cellSelecting';
export var drill = 'drill';
export var cellSelected = 'cellSelected';
export var cellDeselected = 'cellDeselected';
export var rowSelected = 'rowSelected';
export var rowDeselected = 'rowDeselected';
export var beginDrillThrough = 'beginDrillThrough';
export var saveReport = 'saveReport';
export var fetchReport = 'fetchReport';
export var loadReport = 'loadReport';
export var renameReport = 'renameReport';
export var removeReport = 'removeReport';
export var newReport = 'newReport';
export var toolbarRender = 'toolbarRender';
export var toolbarClick = 'toolbarClick';
export var chartTooltipRender = 'chartTooltipRender';
export var chartLoaded = 'chartLoaded';
export var chartLoad = 'chartLoad';
export var chartResized = 'chartResized';
export var chartAxisLabelRender = 'chartAxisLabelRender';
export var chartSeriesCreated = 'chartSeriesCreated';
export var aggregateCellInfo = 'aggregateCellInfo';
export var contextMenuClick = 'contextMenuClick';
export var contextMenuOpen = 'contextMenuOpen';
export var fieldListRefreshed = 'fieldListRefreshed';
export var conditionalFormatting = 'conditionalFormatting';
export var beforePdfExport = 'beforePdfExport';
export var beforeExcelExport = 'beforeExcelExport';
/**
 * Specifies pivot internal events
 */
export var initialLoad = 'initial-load';
export var uiUpdate = 'ui-update';
export var scroll = 'scroll';
export var contentReady = 'content-ready';
export var dataReady = 'data-ready';
export var initSubComponent = 'init-groupingbar';
export var treeViewUpdate = 'tree-view-update';
export var pivotButtonUpdate = 'pivot-button-update';
export var initCalculatedField = 'init-calculatedfield';
export var click = 'click';
export var initToolbar = 'init-toolbar';
export var initFormatting = 'init-formatting';
