import { Calculate } from './index';
export declare class Parser {
    private parent;
    constructor(parent?: Calculate);
    private emptyStr;
    private storedStringText;
    private sheetToken;
    tokenAdd: string;
    tokenSubtract: string;
    tokenMultiply: string;
    tokenDivide: string;
    tokenLess: string;
    private charEm;
    private charEp;
    tokenGreater: string;
    tokenEqual: string;
    tokenLessEq: string;
    tokenGreaterEq: string;
    tokenNotEqual: string;
    tokenAnd: string;
    private tokenEm;
    private tokenEp;
    tokenOr: string;
    private charAnd;
    private charLess;
    private charGreater;
    private charEqual;
    private charLessEq;
    private charGreaterEq;
    private charNoEqual;
    private stringGreaterEq;
    private stringLessEq;
    private stringNoEqual;
    private stringAnd;
    private stringOr;
    private charOr;
    private charAdd;
    private charSubtract;
    private charMultiply;
    private charDivide;
    private fixedReference;
    private spaceString;
    private ignoreBracet;
    isError: boolean;
    isFormulaParsed: boolean;
    private findNamedRange;
    private stringsColl;
    private tokens;
    private charNOTop;
    private specialSym;
    private isFailureTriggered;
    parse(text: string, fkey?: string): string;
    private exceptionArgs;
    private formulaAutoCorrection;
    private checkScopedRange;
    private storeStrings;
    private setStrings;
    parseSimple(formulaText: string): string;
    parseSimpleOperators(formulaText: string, markers: string[], operators: string[]): string;
    indexOfAny(text: string, operators: string[]): number;
    findLeftMarker(text: string): number;
    findRightMarker(text: string): number;
    parseFormula(formula: string, fKey?: string): string;
    markLibraryFormulas(formula: string): string;
    swapInnerParens(fSubstr: string): string;
    addParensToArgs(fSubstr: string): string;
    private lastIndexOfAny;
    markNamedRanges(formula: string): string;
    checkForNamedRangeAndKeyValue(text: string): string;
    private getTableRange;
    private findNextEndIndex;
}
