/**
 * Specifies Workbook internal events.
 */
export declare const workbookDestroyed: string;
export declare const updateSheetFromDataSource: string;
export declare const dataSourceChanged: string;
export declare const workbookOpen: string;
export declare const beginSave: string;
export declare const saveCompleted: string;
export declare const applyNumberFormatting: string;
export declare const getFormattedCellObject: string;
export declare const refreshCellElement: string;
export declare const setCellFormat: string;
export declare const textDecorationUpdate: string;
export declare const applyCellFormat: string;
export declare const updateUsedRange: string;
export declare const workbookFormulaOperation: string;
export declare const workbookEditOperation: string;
export declare const checkDateFormat: string;
export declare const getFormattedBarText: string;
export declare const activeCellChanged: string;
export declare const openSuccess: string;
export declare const openFailure: string;
export declare const sheetCreated: string;
export declare const sheetsDestroyed: string;
export declare const aggregateComputation: string;
export declare const beforeSort: string;
export declare const initiateSort: string;
export declare const sortComplete: string;
export declare const sortRangeAlert: string;
